### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by rickinator9** [hansemannn/titanium-firebase#13]
Hello,

I followed the README for installing this plugin into my Titanium project, but I keep getting this crash on startup. I am using these versions for firebase integration:
- firebase.core: 5.0.0 (Android), 2.2.0 (iPhone)
- firebase.analytics: 3.0.0 (Android), 1.4.1 (iPhone)
- ti.crashlytics: 1.1.1 (Android), 1.2.2 (iPhone)

Is there anything I can do to resolve this error?

2019-07-26 09:57:21.613 26502-26502/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.dtt.checkyoursafety, PID: 26502
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/analytics/connector/AnalyticsConnector;
        at com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar.getComponents(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.<init>(com.google.firebase:firebase-common@@16.1.0:56)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@16.1.0:553)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:365)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:332)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:316)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.1.0:53)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.1.0:47)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6729)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6276)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6191)
        at android.app.ActivityThread.access$1200(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.analytics.connector.AnalyticsConnector" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/nl.dtt.checkyoursafety-sYaqCr7slOU3D7zkKukv7Q==/base.apk"],nativeLibraryDirectories=[/data/app/nl.dtt.checkyoursafety-sYaqCr7slOU3D7zkKukv7Q==/lib/arm64, /data/app/nl.dtt.checkyoursafety-sYaqCr7slOU3D7zkKukv7Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar.getComponents(Unknown Source:2) 
        at com.google.firebase.components.ComponentRuntime.<init>(com.google.firebase:firebase-common@@16.1.0:56) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@16.1.0:553) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:365) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:332) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.1.0:316) 
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.1.0:53) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.1.0:47) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6729) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6276) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6191) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:236) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7037) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by developer82** [comment]
I'm getting the same thing. Were you able to resolve this?

**Comment by hansemannn** [comment]
See https://github.com/hansemannn/titanium-firebase-core/issues/45#issuecomment-507320048
